서버의 JSON 사진 목록을 받아 사진보관함에 다운로드하는 기능 구현
codesquad-member-2020/photos-4 pull request #16
Opened 2020-03-20 05:17 UTC by idevjinie

> 새로 바꾼 점 (step 2 리팩토링)
1. PhotoDataSource 객체에서 사진첩의 변화가 생겼을때 NotifactionCenter.post 을 통해 PhotosViewController가 알도록 하고
PhotosViewController가 변화를 반영하도록 하였습니다. #12
2. ReusableView protocol를 만들고 채택하여 reuseIdentifier를 사용하도록 하였습니다. #11
> 고민하여 구현한 점 (step3)
1. DoodleDataSource객체가 생성될때 json 데이터를 받아와서 디코딩하도록 처리했고, codable 객체가 다 만들어지면 NotificationCenter.post을 이용해 변화를 알려 DoodleViewController가 컬렉션 뷰를 로드하도록 하였습니다. 
2. Codable 객체인 DoodleImageInfo의 속성 date를 처음엔 String으로 두었지만, JSONDecoder를 통해 Date객체로 만들수 있다는 걸 알게 되어 Date 객체로 만들었습니다. #15, #14
3. ImageCollectionCell이라는 protocol를 만들어서 채택하면 cellSize라는 정적 변수를 사용하도록 하였습니다. 
4. Notification.Name객체들을 한 곳에 모으지 않고 사용하는 클래스의 정적 상수로 두어 사용하게끔 하였습니다. 
5. 이미지 다운로드 할때 쓰는 비동기적으로 코드를 구현해야 하는 경우에서 가독성을 위해 if 문을 사용하지 않고 guard문을 사용하였습니다.
6. 스토리보드가 아닌 코드로 구현하다 보니 흐름 파악이 어려웠습니다. 컬렉션뷰의 셀에 커스텀 셀 클래스를 연결하는 부분을 놓쳤었는데 register 메서드로 DoodleCell과 ReuseIdentifier를 지정하였습니다. #10 
7. 특정 셀을 롱클릭할 경우 해당 셀이 아닌 다른 셀에 MenuItem이 표시되었는데, 타겟 범위를 해당 셀의 contentView의 frame으로 지정하여 해결하였습니다. #10

2020-03-20 05:42 UTC, godrm requested changes
다음 피드백을 확인해보세요.

2020-03-20 05:42 UTC, godrm commented on PhotosApp/PhotosApp/Assets.xcassets/github.imageset/Contents.json
> +      "scale" : "3x"
이미지 에셋을 사용할 경우는 고배율을 사용하세요. 이제 1배율을 사용하는 디바이스는 없습니다.

2020-03-20 05:42 UTC, godrm commented on PhotosApp/PhotosApp/DoodleViewController.swift
> +    static let addressAboutDoodleDatas = "https://public.codesquad.kr/jk/doodle.json"
외부에서 필요한게 아니라면 클래스 내부에 넣어도 좋습니다. 참고하세요.

2020-03-20 05:42 UTC, godrm commented on PhotosApp/PhotosApp/DoodleViewController.swift
> +        }
else return 한 줄 뿐이라면 굳이 내려쓰지 않아도 되지 않을까요 (이건 그냥 제 개인 취향일 수도 있지만, 다른 코드가 없는데 굳이 더 길게 할 필요는 없으니까요)

2020-03-20 05:42 UTC, godrm commented on PhotosApp/PhotosApp/DoodleViewController.swift
> +                .notifiactionDoodleImageInfosDidChange,
여러 줄로 내려쓰는 기준은 뭔가요? 상수까지 내려써야 하는 이유는 모르겠어요.

2020-03-20 05:42 UTC, godrm commented on PhotosApp/PhotosApp/Models/DoodleDataSource.swift
> +            else {
guard else 를 이렇게 길게 쓸거면 if else 를 쓰거나 반대로 하는게 좋을 것 같습니다. 
guard else는 else 에서 exit 을 하기 위한 방식입니다.

2020-03-20 05:42 UTC, godrm commented on PhotosApp/PhotosApp/Models/DoodleDataSource.swift
> +        doodleCell.setPhoto(image: doodleImages[itemCount])
- 다운로드 처리하는 로직이 DataSource에 있기 보다는 별도로 분리하는 게 좋겠습니다 .
- 모든 이미지를 배열로 갖고 있는 것은 좋은 선택이 아닙니다. 배열이 커지면 앱이 죽을 수도 있으니까요. 
그래서 셀과 매칭하는 데이터 구조가 별도로 있는 게 좋습니다.

2020-03-20 05:42 UTC, godrm commented on PhotosApp/PhotosApp/Models/PhotosDataSource.swift
> +    }
여기는 이미 기존에 구현한 거 아닌가요? 왜 이전꺼와 비교가 안되죠?

2020-03-20 05:42 UTC, godrm commented on PhotosApp/PhotosApp/Network/Network.swift
> +            completion(data)
한 가지 팁이 있다면, 에러 났을 때 예외처리에 대한 흐름 제어가 꼭 있어야 합니다. 
print()를 쓰지 말고 디버거를 쓰세요. 
completion 핸들러 외에 error 핸들러가 있는 경우도 있습니다.

2020-03-20 05:42 UTC, godrm commented on PhotosApp/PhotosApp/Utils/DataDecoder.swift
> +                    print(error.localizedDescription)
예외 catch 흐름 제어를 꼭 추가하세요.

2020-03-20 05:42 UTC, godrm commented on PhotosApp/PhotosApp/Views/DoodleCell.swift
> +    }
불문율이지만 init()이 가장 먼저 불리니까 다른 메소드들 보다는 위에 선언하는 게 어떨까요?

2020-03-20 05:42 UTC, godrm commented on PhotosApp/PhotosApp/Views/DoodleCell.swift
> +        return doodleImageView.image
아.. 이건 좀 어색합니다. 
저장할 때 뷰에서 이미지를 가져가지 말고, 해당하는 인덱스로 모델에서 참조해서 처리하는 게 좋습니다. 
그러면 여기 photo() 메소드는 필요없겠죠.

2020-03-20 07:01 UTC, ehgud0670 commented on PhotosApp/PhotosApp/DoodleViewController.swift
> +    static let addressAboutDoodleDatas = "https://public.codesquad.kr/jk/doodle.json"
넵 반영하였습니다. 감사합니다.

2020-03-21 05:39 UTC, idevjinie commented on PhotosApp/PhotosApp/Views/DoodleCell.swift
> +        return doodleImageView.image
모델에서 해당 인덱스를 사용하여 처리하도록 변경하였습니다. 모델과 뷰의 역할에 유의하겠습니다.

2020-03-21 05:47 UTC, ehgud0670 commented on PhotosApp/PhotosApp/DoodleViewController.swift
> +        }
아 넵, 제가 생각해도 return 한줄만 있는 경우에는 안 내려쓰는게 나을 것 같아요. 반영하였습니다. 감사합니다.

2020-03-21 05:47 UTC, idevjinie commented on PhotosApp/PhotosApp/Views/DoodleCell.swift
> +    }
혹시 다른 메소드들이라는 것이 무엇을 지칭하는지 설명해주실 수 있나요?

2020-03-21 05:50 UTC, idevjinie commented on PhotosApp/PhotosApp/Assets.xcassets/github.imageset/Contents.json
> +      "scale" : "3x"
디바이스별 디스플레이와 이미지 에셋의 관계에 대해 학습하였습니다. 해당 테스트용 이미지는 삭제하였습니다.

2020-03-21 05:56 UTC, ehgud0670 commented on PhotosApp/PhotosApp/DoodleViewController.swift
> +                .notifiactionDoodleImageInfosDidChange,
아 99자를 넘어가서 내려썼습니다. 근데 생각해보니 더 가독성을 해치는 것 같습니다. 
```swift
        NotificationCenter.default.addObserver(forName: DoodleDataSource.notifiactionDoodleImageInfosDidChange,
                                               object: doodleDataSource,
                                               queue: nil) { [weak self] _ in
                                                DispatchQueue.main.async {
                                                    self?.reloadCollectionView()
                                                }
        }
```
이런식으로 바꿨습니다. 감사합니다.

2020-03-21 05:59 UTC, ehgud0670 commented on PhotosApp/PhotosApp/Models/PhotosDataSource.swift
> +    }
아 기존에 구현했던건데 폴더 Models에 옮겨나서 비교가 안됐던 것 같습니당

2020-03-21 06:24 UTC, ehgud0670 commented on PhotosApp/PhotosApp/Models/DoodleDataSource.swift
> +            else {
넵넵 guard else에서 else문은 exit 하는 경우에만 코드를 작성하도록 하겠습니다. 
해당 코드는 if else문을 작성하였습니다. 감사합니다.

2020-03-21 07:13 UTC, godrm commented on PhotosApp/PhotosApp/Views/DoodleCell.swift
> +    }
여기 init보다 위에 선언한 func 메소드들이요
파일을 위에서부터 읽는 순서를 호출되는 순서와 비슷하게 하는게 좋습니다

2020-03-21 07:19 UTC, ehgud0670 commented on PhotosApp/PhotosApp/Views/DoodleCell.swift
> +    }
func 메소드 없지 않나요 ㅜ 
혹시 연산 프로퍼티 `canBecomeFirstResponder`나 클로저로 생성시킬 `doodleImageView` 프로퍼티를 말씀하시는 건가요?

2020-03-21 07:27 UTC, godrm commented on PhotosApp/PhotosApp/Views/DoodleCell.swift
> +    }
어라 이 클래스가 아니라 다른 클래스에 대한 건가 
모바일에서 위에 코드가 안 보이는데 다른 클래스도 확인해보세요

2020-03-21 07:31 UTC, ehgud0670 commented on PhotosApp/PhotosApp/Views/DoodleCell.swift
> +    }
아 넵, 알겠습니다

2020-03-21 07:34 UTC, ehgud0670 commented on PhotosApp/PhotosApp/Views/DoodleCell.swift
> +    }
혹시 
혹시 DoodleDataSource 클래스의 아래 코드 말씀하시는건가요??
```swift
    private var doodleImageInfos = [DoodleImageInfo]() {
        didSet {
            NotificationCenter.default.post(name: DoodleDataSource.notifiactionDoodleImageInfosDidChange,
                                            object: self)
        }
    }
```

2020-03-21 07:35 UTC, ehgud0670 commented on PhotosApp/PhotosApp/Models/DoodleDataSource.swift
> +        doodleCell.setPhoto(image: doodleImages[itemCount])
넵, NSCache를 적용해보도록 하겠습니다. 가능하면 디스크에 데이터를 저장하도록 하겠습니다.

2020-03-21 07:40 UTC, ehgud0670 commented on PhotosApp/PhotosApp/Network/Network.swift
> +            completion(data)
아 에러났을때 디버거를 사용하면 print()을 안써도 되는 군요. 알겠습니다. print문은 지우도록 하고 에러 났을때 예외 처리를
해보도록 하겠습니다.

2020-03-21 08:23 UTC, godrm commented on PhotosApp/PhotosApp/Models/DoodleDataSource.swift
> +        doodleCell.setPhoto(image: doodleImages[itemCount])
NSCache가 다운로드를 대신해주거나 관리해주는 건 아닙니다. 
앱에서 파일을 다운로드해서 어디에 저장하는지 공부해보세요.

2020-03-21 08:27 UTC, ehgud0670 commented on PhotosApp/PhotosApp/Models/DoodleDataSource.swift
> +        doodleCell.setPhoto(image: doodleImages[itemCount])
아 넵넵 👍

2020-03-21 08:41 UTC, ehgud0670 commented on PhotosApp/PhotosApp/Views/DoodleCell.swift
> +    }
doodleImageInfos 프로퍼티를 사용하는 메소드 아래에 위치해둠으로써 문제를 해결하였습니다.

2020-03-28 06:10 UTC, ehgud0670 commented
예외 처리와 디스크에 저장하는 것을 제외하고 피드백 모두 반영하였습니다. 예외 처리와 디스크에 저장하는 것은 오늘 해볼 예정입니다.

2020-06-11 04:56 UTC, godrm commented on PhotosApp/PhotosApp/DoodleViewController.swift
> +    }
여기 ViewController에서는 token을 지정하는 곳이 없는데요?

2020-06-11 04:57 UTC, godrm commented on PhotosApp/PhotosApp/PhotosViewController.swift
> +        token = NotificationCenter.default.addObserver(forName: PhotosDataSource.notificationPhotoLibraryDidChange,
그리고보니 token 이라는 변수 이름도 어색하네요. observer 역할 아닌가요?

2020-06-11 05:18 UTC, ehgud0670 commented on PhotosApp/PhotosApp/PhotosViewController.swift
> +        token = NotificationCenter.default.addObserver(forName: PhotosDataSource.notificationPhotoLibraryDidChange,
네, 맞습니다. https://developer.apple.com/documentation/foundation/notificationcenter/1411723-addobserver 의 예제보고 아무생각 없이 token이라고 했네요 😅 수정하도록 하겠습니다. 👍

2020-06-11 05:26 UTC, ehgud0670 commented on PhotosApp/PhotosApp/DoodleViewController.swift
> +    }
아 실수했습니다. 다시 반영하도록 하겠습니다.

2020-06-11 05:30 UTC, ehgud0670 commented on PhotosApp/PhotosApp/DoodleViewController.swift
> +    }
반영했습니다.

2020-06-11 05:31 UTC, ehgud0670 commented on PhotosApp/PhotosApp/PhotosViewController.swift
> +        token = NotificationCenter.default.addObserver(forName: PhotosDataSource.notificationPhotoLibraryDidChange,
반영했습니다.

2020-06-11 05:34 UTC, godrm commented
수고하셨습니다.

2020-06-11 05:35 UTC, ehgud0670 commented
사실 임시로 push 한거라 pr이 다시 살아날줄 몰랐습니다. ㅋㅋㅋ 
기왕 열려진거 지금 코드는 
1) Image Data를 프로퍼티로 가지고 있고, 
2) 이미지도 업데이트가 안되는데

메모리 낭비를 줄이기 위해 Data 프로퍼티를 삭제하고, 이미지도 업데이트될 수 있게끔만 구현해보도록 하겠습니다~!

2020-06-11 05:37 UTC, godrm commented
PR 안 닫힌 상태에서 그냥 Push 해서 그런가보네요. 이거 닫고 개선해서 다시 보내세요. 
그래야 구분이 될 것 같네요.

2020-06-11 05:48 UTC, ehgud0670 commented
아 넵넵 감사합니다

2020-07-02 05:11 UTC, merged