[Step2] 미션 제출합니다.
codesquad-member-2020/photos-4 pull request #9
Opened 2020-03-17 09:57 UTC by ehgud0670

> 안되는 점 

cell을 100x100으로 설정하고 썸네일 이미지도 마찬가지로 같은 크기로 설정했는데 
반영이 되지 않습니다...
커스텀 콜렉션뷰셀 객체인 PhotoCell에 이미지뷰 추가하고 오토레이아웃을 cell에 딱 맞게 설정해서 잘 될 것 같았는데 안되네요... ㅜㅜ

2020-03-17 10:19 UTC, godrm requested changes
페어로 작업하면서 잘 구현한 것 같습니다. 다음 내용을 확인해서 개선해보고, 항목별로 댓글을 남겨주세요.

2020-03-17 10:19 UTC, godrm commented on PhotosApp/PhotosApp/Assets.xcassets/cantata-primiumlatte-175ml.imageset/Contents.json
> +      "scale" : "3x"
이미지 에셋에 배율이 다른걸 사용하고 있네요?
이제 1배율 이미지는 사용하는 디바이스가 없습니다. 2x 나 3x를 사용하세요.

2020-03-17 10:19 UTC, godrm commented on PhotosApp/PhotosApp/PhotosDataSource.swift
> +    static let photosCell = "photosCell"
셀이 추가될 때마다 여기에 identifier를 모을꺼간요?
자꾸 값들마다 모으지 마시고, 객체마다 고유한 값, 기능, 속성을 갖도록 모으세요. 
이 값은 누구의 것일까요?

2020-03-17 10:19 UTC, godrm commented on PhotosApp/PhotosApp/PhotosDataSource.swift
> +        allPhotos = PHAsset.fetchAssets(with: .image, options: nil)
이렇게 전체 사진을 다 가져오는 게 시뮬레이터 상에서는 전혀 문제가 되지 않지만, 폰에서는 문제가 될 수도 있습니다.
직접 (사진이 많은) 폰에 물려서 느리지 않은지 확인하세요. 앱을 실행하면서 바로 뜨지 않으면 느린 겁니다.

2020-03-17 10:19 UTC, godrm commented on PhotosApp/PhotosApp/PhotosDataSource.swift
> +                                        options: nil)
사진이 많으면 전체 이미지 썸네일을 만드는 작업도 오래 걸릴 수 있습니다. 이게 항상 좋은 구조는 아닙니다.

2020-03-17 10:19 UTC, godrm commented on PhotosApp/PhotosApp/ViewController.swift
> +import Photos
ViewController가 Photos 프레임워크에 의존하지 않고 독립적으로 동작하도록 개선해보세요.
PhotosDataSource 만 알고 있어도 충분히 동작 가능하지 않을까요?

2020-03-17 10:19 UTC, godrm commented on PhotosApp/PhotosApp/ViewController.swift
> +        photosDataSource.sharePhotoLibraryChanges()
데이터 소스에 초기화하기 위해서 불러야 하는 메소드가 여러 개라면 어떤 메소드를 어떤 순서로 해야하는 지 헷갈릴 수 있습니다.
생성하면서 초기화가 다 되고 동작하는 메소드 정도로 구분해보세요.

2020-03-17 10:19 UTC, godrm commented on PhotosApp/PhotosApp/Views/PhotoCell.swift
> +        setupPhotoImageView()
한 줄짜리 메소드를 부르는 건 왜 분리한건가요? setupPhotoImageView() 함수 내용이 여기 있어도 되는거 아닐까요?

2020-03-17 10:19 UTC, godrm commented on PhotosApp/PhotosApp/Views/PhotoCell.swift
> +        return imageView
커스텀 셀을 선언하고 스토리보드에서 디자인하지 않고 코드로 작성했네요. 
스토리보드에서 하는 것과 코드로 하는 경우에 속성에 기본적으로 채우는 값이 다릅니다. 
이미지가 그대로 다 보이는 것은 bounds 와 관련이 있습니다. 찾아보세요.

2020-03-17 11:16 UTC, idevjinie commented on PhotosApp/PhotosApp/ViewController.swift
> +import Photos
네, PhotosDataSource만 Photo 프레임워크에 의존하도록 코드를 반영하였습니다.

2020-03-17 11:24 UTC, idevjinie commented on PhotosApp/PhotosApp/Views/PhotoCell.swift
> +        setupPhotoImageView()
나중에 설정하는 코드가 길어질 경우를 대비해서 메소드를 분리했었는데 그냥 지금은 분리하지 않고 나중에 코드가 길어진다면 분리하도록 하겠습니다! 코드 반영하였습니다.

2020-03-17 11:34 UTC, idevjinie commented on PhotosApp/PhotosApp/ViewController.swift
> +        photosDataSource.sharePhotoLibraryChanges()
하나의 메서드에서 설정 관련 메서드들을 호출하도록 변경하였습니다.

2020-03-17 12:17 UTC, idevjinie commented on PhotosApp/PhotosApp/PhotosDataSource.swift
> +    static let photosCell = "photosCell"
PhotoCell이 고유한 identifier를 갖도록 PhotoCell에 정적 속성을 추가하여 반영하였습니다.

2020-03-17 12:19 UTC, idevjinie commented on PhotosApp/PhotosApp/Assets.xcassets/cantata-primiumlatte-175ml.imageset/Contents.json
> +      "scale" : "3x"
네, 참고하겠습니다. 해당 이미지 파일은 사용하지 않아 삭제하였습니다.

2020-03-17 13:09 UTC, godrm commented on PhotosApp/PhotosApp/PhotosDataSource.swift
> +        let reuseIdentifier = PhotoCell.identifier
뭐 이 정도는 그냥 PhotoCell.identifier를 써도 될 것 같네요.

2020-03-17 13:10 UTC, godrm commented on PhotosApp/PhotosApp/ViewController.swift
> +                                      forCellWithReuseIdentifier: PhotoCell.identifier)
스토리보드에서 셀을 디자인한 경우는 register 하지 않아도 동작할 겁니다. 확인해보세요.

2020-03-17 13:10 UTC, godrm commented
수고하셨습니다.

2020-03-17 13:42 UTC, ehgud0670 commented on PhotosApp/PhotosApp/Views/PhotoCell.swift
> +        return imageView
코드로 구현을 해봤는데 안되서 스토리보드에서 디자인하여 해결하였습니다.

2020-03-17 15:00 UTC, godrm commented
머지하셔도 될 것 같아요.

2020-03-18 02:18 UTC, ehgud0670 commented on PhotosApp/PhotosApp/PhotosDataSource.swift
> +        let reuseIdentifier = PhotoCell.identifier
Jk 혹시 더 좋은 방법이 있을까요??

2020-03-18 02:19 UTC, ehgud0670 commented
앗 아직 다 못한것 같아서 더 해보고 머지하도록 하겠습니다 ㅎㅎ

2020-03-18 02:25 UTC, godrm commented on PhotosApp/PhotosApp/PhotosDataSource.swift
> +        let reuseIdentifier = PhotoCell.identifier
let 으로 지정하지 않아도 충분하다는 의미였어요. 어차피 상수인걸요

2020-03-18 02:27 UTC, ehgud0670 commented on PhotosApp/PhotosApp/PhotosDataSource.swift
> +        let reuseIdentifier = PhotoCell.identifier
아 맞네용 ㅋㅋㅋ넵 알겟슴다 ㅎㅎ

2020-03-18 02:47 UTC, ehgud0670 commented on PhotosApp/PhotosApp/PhotosDataSource.swift
> +        allPhotos = PHAsset.fetchAssets(with: .image, options: nil)
문서를 봤는데도 다른 방법은 잘 모르겠습니다... 😭혹시 참조할만한 사이트 있으신가요??

2020-03-18 02:51 UTC, ehgud0670 commented on PhotosApp/PhotosApp/PhotosDataSource.swift
> +                                        options: nil)
넵, 알겠습니당
https://developer.apple.com/documentation/photokit/phcachingimagemanager 여기 문서보고 순서대로 적용해봤는데 일단은 이 구조로 가보도록 하겠습니다 ㅎㅎ

2020-03-18 03:00 UTC, ehgud0670 commented on PhotosApp/PhotosApp/ViewController.swift
> +                                      forCellWithReuseIdentifier: PhotoCell.identifier)
아 넵 제거하였습니다.

2020-03-18 05:49 UTC, ehgud0670 commented
옵저버를 이용하여 사진보관함이 변경되면 CollectionView에 반영되도록 기능구현하였습니다. 
다 했으므로 머지하고 step3 진행하겠습니다.

2020-03-18 05:49 UTC, merged